apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    tier: postgres-db
spec:
  containers:
    - name: postgres-db
      image: postgres:alpine3.18
      resources:
        limits:
          memory: '128Mi'
          cpu: '250m'
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: 'postgres'

---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  selector:
    tier: postgres-db
  ports:
    - port: 5432
      targetPort: 5432
