apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    tier: redis-db
spec:
  containers:
    - name: redis-container
      image: redis:7.2.4-alpine
      ports:
        - containerPort: 6379
      resources:
        limits:
          memory: '128Mi'
          cpu: '250m'
