apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    tier: redis-db
spec:
  containers:
    - name: redis-container
      image: redis:7.2.4-alpine
      resources:
        limits:
          memory: '128Mi'
          cpu: '250m'

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    tier: redis-db
  