apiVersion: v1
kind: Service
metadata:
  name: vote-result-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    tier: vote-result-frontend
