apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-result
  labels:
    app: vote-result
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: vote-result-frontend
  template:
    metadata:
      name: vote-result-frontend
      labels:
        tier: vote-result-frontend
    spec:
      containers:
        - name: vote-result-frontend
          image: silanka/va-k8s-result
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: '128Mi'
              cpu: '250m'
