apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app
  labels:
    tier: backend
spec:
  selector:
    matchLabels:
      tier: worker-app-backend
  replicas: 1
  template:
    metadata:
      name: worker-app-backend
      labels:
        tier: worker-app-backend
    spec:
      containers:
        - name: worker-app-backend
          image: silanka/va-k8s-worker
          resources:
            limits:
              memory: '128Mi'
              cpu: '250m'
